# iConomyDeath's configuration file.
#
# This is the a per-world configuration file. It only affects one
# corresponding world.

percentage: true # Enable to use percentage or disable for simple amount.
value: 1.0 # Amount or percentage.
